segmentation:
  ros__parameters:
    input.image_topic: /zed/zed_node/rgb/color/rect/image
    model.path: ""
    model.device: "0"
    model.confidence: 0.25
    model.image_size: 960
    model.iou: 0.60
